### ISSUE TITLE
Brakujący plik

### ISSUE THREAD

**Issue by Andrzej14334** [Goral64/gui-generic-builder-online#1]
Otrzymuję komunikat błędu o brakującym pliku Adafruit_BusIO_Register.cpp, jest możliwość uzupełnienia? Problem pojawia się przy zaznaczeniu funkcji termostatu.

.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.1.0-gcc10.3-e5f9fec/bin/xtensa-lx106-elf-ar: /tmp/arduino/sketches/D7ACCE04F189B466DAC53E1D8DD5797B/libraries/Adafruit_BusIO/Adafruit_BusIO_Register.cpp.o: No such file or directory
Multiple libraries were found for "SoftwareSerial.h"
  Used: /var/www/html/github/GUI-Generic/lib/EspSoftwareSerial
  Not used: /var/www/html/github/GUI-Generic/lib/EspSoftwareSerial
  Not used: .arduino15/packages/esp8266/hardware/esp8266/3.1.2/libraries/SoftwareSerial
Error during build: exit status 1
xxxxxxxxxxxxxxxxxx
BOARD esp8266:esp8266:generic:eesz=1M64,xtal=160
BOARD_NAME
TEMPLATE_JSON
JSON_DEFINITION
OPTIONS -DATOMIC_FS_UPDATE -DMIMETYPE_MINIMAL -DBEARSSL_SSL_BASIC -DNDEBUG -DSUPLA_CONFIG -DSUPLA_DISABLE_LOGS -DSUPLA_DS18B20 -DSUPLA_ENABLE_GUI 
-DSUPLA_EXCLUDE_LITTLEFS_CONFIG -DSUPLA_LED -DSUPLA_OTA -DSUPLA_RELAY -DSUPLA_THERMOSTAT

**Comment by Goral64** [comment]
To jest problem kodów źródłowych GUI-Generic. Można takie problemy zgłaszać na forum Supli
https://forum.supla.org/viewforum.php?f=88
